name: brew_me_coffee
description: Brew Me Coffe - A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  provider: ^4.0.2
  flutter_spinkit: ^4.1.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/coffee_bg.png
    - assets/coffee_icon.png
